name: Deploy my Application to EC2 and Run as a docker container

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/exchange-rate-app:latest
          ${{ secrets.DOCKER_USERNAME }}/exchange-rate-app:${{ github.sha }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/exchange-rate-app:latest
          docker stop exchange-rate-app || true
          docker rm exchange-rate-app || true
          docker run -d --name exchange-rate-app -p 80:5000 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/exchange-rate-app:latest